Feature/at resources 23
at-internship/at-resources-api pull request #7
Opened 2020-11-03 02:20 UTC by KevinRSantillan

PUT Implementing

2020-11-03 02:40 UTC, at-internship requested changes, later dismissed
`bin` folder must not be versioned

2020-11-04 16:29 UTC, rodrigo-velasco approved these changes

2020-11-04 20:55 UTC, ivanflores15 approved these changes

2020-11-04 21:49 UTC, ivanflores15 approved these changes

2020-11-04 21:56 UTC, carla-paz commented
> `bin` folder must not be versioned

The issue has been resolved. The bins were removed.

2020-11-04 21:59 UTC, merged